export default {
    '01': 'CREACION_DE_OBRA',
    '02': 'OBRA_EN_PRESUPUESTACION',
    '03': 'OBRA_ESPERANDO_LIBERACION',
    '04': 'OBRA_EN_PLANIFICACION',
    '05': 'EN_EJECUCION',
    '06': 'SOLICITUD_DE_PRECIERRE',
    '07': 'OBRA/INGENIERIA_EN_PRECIERRE',
    '08': 'PROYECTO_FINALIZADO_EJECUTADO',
    '09': 'PROYECTO_CANCELADO',
    '10': 'PROYECTO_EN_STAND_BY',
}